language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - 1.1
  - nightly
arch:
  - x86
  - x64
matrix:
  exclude:
    - os: osx
      arch: x86
notifications:
  email: false
coveralls: true
